build:
  version: "1.0"

loans:
  message: "Welcome to ArifBank loans Service PROD API"
  contactDetails:
    name: "Ariful Islam - Developer"
    email: "arifcse209@gmail.com"
  onCallSupport:
    - 8801712345678

