spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/devarifkhan/microservice-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "72917435e3a637749b2abdb9bce96ddf66950fef88b8e62243cb9518fe017359b591368b18792f78db612d30e9782847"

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"