spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        #        native:
        #          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/devarifkhan/microservice-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoint:
    web:
      exposure:
        include: "*"

server:
  port: 8071
encrypt:
  key: "G7#pL9@qX2!zR4&vT8^sW1%yM3*oN5(qP6)jK0_eF"